apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: db-config
  data:
    DB_NAME: "${DB_NAME}"
    DB_USER: "${DB_USER}"
    DB_PASS: "${DB_PASS}"
    DB_HOST: "${DB_HOST}"
    DB_PORT: "${DB_PORT}"
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: finance-db-config
  data:
    FINANCE_DB_NAME: "${FINANCE_DB_NAME}"
    FINANCE_DB_USER: "${FINANCE_DB_USER}"
    FINANCE_DB_PASS: "${FINANCE_DB_PASS}"
    FINANCE_DB_HOST: "${FINANCE_DB_HOST}"
    FINANCE_DB_PORT: "${FINANCE_DB_PORT}"
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: data-service-config
  data:
    DATA_SERVICE_HOST: "${DATA_SERVICE_HOST}"
    DATA_SERVICE_PORT: "${DATA_SERVICE_PORT}"
- apiVersion: v1
  kind: Pod
  metadata:
    name: finance-data-service-sync
  spec:
    containers:
    - name: finance-data-service-sync
      image: innovateuk/finance-data-service-sync:1.0-SNAPSHOT
      imagePullPolicy: Always
      command: [ "/bin/sh", "-exec" ]
      args:
      - ./send-all-cost-totals.sh
      env:
      - name: DB_HOST
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: DB_HOST
      - name: DB_PORT
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: DB_PORT
      - name: DB_NAME
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: DB_NAME
      - name: DB_USER
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: DB_USER
      - name: DB_PASS
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: DB_PASS
      - name: FINANCE_DB_HOST
        valueFrom:
          configMapKeyRef:
            name: finance-db-config
            key: FINANCE_DB_HOST
      - name: FINANCE_DB_PORT
        valueFrom:
          configMapKeyRef:
            name: finance-db-config
            key: FINANCE_DB_PORT
      - name: FINANCE_DB_NAME
        valueFrom:
          configMapKeyRef:
            name: finance-db-config
            key: FINANCE_DB_NAME
      - name: FINANCE_DB_USER
        valueFrom:
          configMapKeyRef:
            name: finance-db-config
            key: FINANCE_DB_USER
      - name: FINANCE_DB_PASS
        valueFrom:
          configMapKeyRef:
            name: finance-db-config
            key: FINANCE_DB_PASS
      - name: DATA_SERVICE_HOST
        valueFrom:
          configMapKeyRef:
            name: data-service-config
            key: DATA_SERVICE_HOST
      - name: DATA_SERVICE_PORT
        valueFrom:
          configMapKeyRef:
            name: data-service-config
            key: DATA_SERVICE_PORT
    restartPolicy: Never