version: '3'
services:

  finance-data-service:
    image: innovateuk/finance-data-service
    healthcheck:
      test: ["CMD", "curl", "-f",  "http://localhost:8080/monitoring/health"]
      interval: 15s
      timeout: 8s
    networks:
      ifs:
        aliases:
          - ifs-finance-data-service
