version: '3'
services:

  assessment-svc:
    image: innovateuk/assessment-service
    healthcheck:
      test: ["CMD", "curl", "-f",  "http://localhost:8080/assessment/monitoring/health"]
      interval: 15s
      timeout: 8s
    networks:
      - ifs
    hostname: assessment-svc


  competition-mgt-svc:
    image: innovateuk/competition-mgt-service
    healthcheck:
      test: ["CMD", "curl", "-f",  "http://localhost:8080/management/monitoring/health"]
      interval: 15s
      timeout: 8s
    networks:
      - ifs
    hostname: competition-mgt-svc

  project-setup-mgt-svc:
    image: innovateuk/project-setup-mgt-service
    healthcheck:
      test: ["CMD", "curl", "-f",  "http://localhost:8080/project-setup-management/monitoring/health"]
      interval: 15s
      timeout: 8s
    networks:
      - ifs
    hostname: project-setup-mgt-svc


  project-setup-svc:
    image: innovateuk/project-setup-service
    healthcheck:
      test: ["CMD", "curl", "-f",  "http://localhost:8080/project-setup/monitoring/health"]
      interval: 15s
      timeout: 8s
    networks:
      - ifs
    hostname: project-setup-svc


  front-door-svc:
    image: innovateuk/front-door-service
    healthcheck:
      test: ["CMD", "curl", "-f",  "http://localhost:8080/monitoring/health"]
      interval: 15s
      timeout: 8s
    networks:
      - ifs
    hostname: front-door-svc

