version: '3'
services:

  finance-data-service:
    image: innovateuk/finance-data-service
    healthcheck:
      test: ["CMD", "curl", "-f",  "http://localhost:8080/monitoring/health"]
      interval: 15s
      timeout: 8s
    networks:
      ifs:
        aliases:
          - ifs-finance-data-service
    hostname: finance-data-service
    ports:
      - "8092:8080"
      - "9012:8000"
    environment:
      - JAVA_OPTS=-Xmx300m -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n

  ifs-finance-database:
    image: innovateuk/ifs-mysql:5.6.29
    ports:
      - "3307:3306"
    command: [--character-set-server=utf8, --collation-server=utf8_bin]
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ifs_finance
    restart: on-failure
    networks:
      - ifs

networks:
  ifs:
    driver: bridge