version: '3'
services:

  assessment-svc:
    image: innovateuk/assessment-service
    healthcheck:
      test: ["CMD", "curl", "-f",  "http://localhost:8080/assessment/monitoring/health"]
      interval: 15s
      timeout: 8s
    networks:
      - ifs
    hostname: assessment-svc
    ports:
      - "8082:8080"
      - "9002:8000"
    environment:
      - JAVA_OPTS=-Xmx300m -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n


  competition-mgt-svc:
    image: innovateuk/competition-mgt-service
    healthcheck:
      test: ["CMD", "curl", "-f",  "http://localhost:8080/management/monitoring/health"]
      interval: 15s
      timeout: 8s
    networks:
      - ifs
    hostname: competition-mgt-svc
    environment:
      - JAVA_OPTS=-Xmx300m -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n
    ports:
      - "8083:8080"
      - "9003:8000"

  project-setup-mgt-svc:
    image: innovateuk/project-setup-mgt-service
    healthcheck:
      test: ["CMD", "curl", "-f",  "http://localhost:8080/project-setup-management/monitoring/health"]
      interval: 15s
      timeout: 8s
    networks:
      - ifs
    hostname: project-setup-mgt-svc
    ports:
      - "8084:8080"
      - "9004:8000"
    environment:
      - JAVA_OPTS=-Xmx300m -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n


  project-setup-svc:
    image: innovateuk/project-setup-service
    healthcheck:
      test: ["CMD", "curl", "-f",  "http://localhost:8080/project-setup/monitoring/health"]
      interval: 15s
      timeout: 8s
    networks:
      - ifs
    hostname: project-setup-svc
    ports:
      - "8085:8080"
      - "9005:8000"
    environment:
      - JAVA_OPTS=-Xmx300m -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n


  front-door-svc:
    image: innovateuk/front-door-service
    healthcheck:
      test: ["CMD", "curl", "-f",  "http://localhost:8080/monitoring/health"]
      interval: 15s
      timeout: 8s
    networks:
      - ifs
    hostname: front-door-svc
    ports:
      - "8087:8080"
      - "9007:8000"
    environment:
      - JAVA_OPTS=-Xmx300m -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n

