version: '3'
services:

  prototypes-svc:
    hostname: prototypes-svc
    image: innovateuk/prototypes-service
    healthcheck:
       test: ["CMD", "curl", "-f",  "http://localhost:8080/monitoring/health"]
       interval: 15s
       timeout: 8s
    ports:
      - "1234:8080"
    networks:
      - ifs

networks:
  ifs:
    driver: bridge
