apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: idp
  spec:
    replicas: 1
    selector:
      deploymentconfig: idp
    strategy:
      type: Rolling
      rollingParams:
        timeoutSeconds: 600
        maxSurge: 2
        maxUnavailable: 0
    template:
      metadata:
        labels:
          deploymentconfig: idp
      spec:
        containers:
        - image: innovateuk/idp-service:1.0-SNAPSHOT
          name: idp
          livenessProbe:
            httpGet:
              path: /idp/status
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /idp/status
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 1
          imagePullPolicy: Always
          env:
          - name: JAVA_OPTS
            value: -Xms384M -Xmx768M -javaagent:/newrelic.jar
          - name: NEW_RELIC_APP_NAME
            value: "ifs-idp-service (<<NEWRELIC-ENVIRONMENT>>)"
          - name: NEW_RELIC_LICENSE_KEY
            value: "<<NEWRELIC-LICENCE-KEY>>"
          - name: NEW_RELIC_LOG
            value: "STDOUT"
          - name: IDP_PROXY_CERTIFICATE
            value: "<<SSLCERT>>"
          - name: IDP_PROXY_CACERTIFICATE
            value: "<<SSLCACERT>>"
          - name: IDP_PROXY_KEY
            value: "<<SSLKEY>>"
          - name: SP_PROXY_CERTIFICATE
            value: "<<SSLCERT>>"
          - name: SP_DOMAIN
            value: <<SHIB-ADDRESS>>
          - name: IDP_DOMAIN
            value: <<SHIB-IDP-ADDRESS>>
          - name: HTTPS_PORT
            value: "9443"
          - name: HTTP_PORT
            value: "9080"
          - name: MEMCACHE_ENDPOINT
            value: "<<SHIBBOLETH-MEMCACHE-ENDPOINT>>"
          - name: LDAP_URL
            value: "<<LDAP-URL>>"
          - name: LDAP_PORT
            value: "389"
          - name: LDAP_USESTARTTLS
            value: "false"
          - name: LDAP_USESSL
            value: "<<LDAP_USE_SSL>>"
          - name: LDAP_BASEDN
            value: "<<LDAP_BASEDN>>"
          - name: LDAP_BINDDN
            value: "<<LDAP_BINDDN>>"
          - name: LDAP_BINDDNCREDENTIAL
            value: "<<LDAP-PASSWORD>>"
          - name: LDAP_USERFILTER
            value: "(&(mail={user})(!(employeeType=inactive)))"
          - name: LDAP_ATTRIBUTE_SEARCHFILTER
            value: "(mail=$resolutionContext.principal)"
          - name: LDAP_RETURNATTRIBUTES
            value: "mail,uid"
          - name: LDAP_AUTHENTICATOR
            value: "<<LDAP_AUTHENTICATOR>>"
          - name: GOOGLEANALYTICS_TRACKINGID
            value: "<<GA-TRACKING-ID>>"
          ports:
          - containerPort: 9443
          - containerPort: 9080
          resources:
            requests:
              memory: "<<SHIBBOLETH_IDP_MEMORY_REQUEST>>"
            limits:
              memory: "<<SHIBBOLETH_IDP_MEMORY_LIMIT>>"
          test: false
  triggers:
  - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    name: idp
  spec:
    ports:
    - name: 443-tcp
      port: 443
      targetPort: 9443
    selector:
      deploymentconfig: idp
  status:
    loadBalancer: {}

- apiVersion: v1
  kind: Route
  metadata:
    name: idp
  spec:
    host: <<SHIB-IDP-ADDRESS>>
    port:
      targetPort: 443-tcp
    tls:
      termination: passthrough
    to:
      kind: Service
      name: idp
